In [78]:
Data Exploration

SyntaxError: invalid syntax (4001574206.py, line 1)

In [ ]:
import pandas as pd

In [ ]:
import seaborn as sns

In [ ]:
data = pd.read_csv("C:/Users/abass/OneDrive/Desktop/STATISTICAL TOOLS/PYTHON/Data/classwork-week 3 day 1.csv")
data

,OrderID,OrderDate,Customer,Gender,Department,StaffSalary,ProductCategory,Quantity,UnitPrice,Revenue
0,1001.0,05/01/2025,C001,Female,Sales,500.0,Electronics,2.0,250.0,500.0
1,1002.0,07/01/2025,C002,Male,Support,400.0,Fashion,3.0,50.0,150.0
2,1003.0,10/01/2025,C003,Female,Sales,NaN,Electronics,1.0,300.0,300.0
3,1004.0,12/01/2025,C004,Male,Marketing,600.0,Groceries,10.0,20.0,200.0
4,1005.0,15/01/2025,C005,Female,Sales,500.0,Fashion,2.0,80.0,160.0
5,1006.0,20/01/2025,C006,Male,Support,400.0,Electronics,5.0,220.0,1100.0
6,1007.0,22/01/2025,C007,Female,Marketing,600.0,Fashion,1.0,100.0,100.0
7,1008.0,25/01/2025,C008,Male,Sales,500.0,Groceries,20.0,15.0,300.0
8,1009.0,28/01/2025,C009,Female,Support,400.0,Fashion,2.0,60.0,120.0
9,1010.0,01/02/2025,C010,Male,Sales,500.0,Electronics,1.0,500.0,500.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          10 non-null     float64
 1   OrderDate        10 non-null     object
 2   Customer         10 non-null     object
 3   Gender           10 non-null     object
 4   Department       10 non-null     object
 5   StaffSalary      9 non-null      float64
 6   ProductCategory  10 non-null     object
 7   Quantity         10 non-null     float64
 8   UnitPrice        10 non-null     float64
 9   Revenue          10 non-null     float64
dtypes: float64(5), object(5)
memory usage: 1.3+ KB

In [ ]:
data.describe()

          OrderID  StaffSalary   Quantity   UnitPrice      Revenue
count    10.00000     9.000000  10.000000   10.000000    10.000000
mean   1005.50000   488.888889   4.700000  159.500000   343.000000
std       3.02765    78.173596   6.037844  156.212996   302.950308
min    1001.00000   400.000000   1.000000   15.000000   100.000000
25%    1003.25000   400.000000   1.250000   52.500000   152.500000
50%    1005.50000   500.000000   2.000000   90.000000   250.000000
75%    1007.75000   500.000000   4.500000  242.500000   450.000000
max    1010.00000   600.000000  20.000000  500.000000  1100.000000

In [ ]:
selection = data[['Department','StaffSalary','Revenue']]
selection

   Department  StaffSalary  Revenue
0       Sales        500.0    500.0
1     Support        400.0    150.0
2       Sales          NaN    300.0
3   Marketing        600.0    200.0
4       Sales        500.0    160.0
5     Support        400.0   1100.0
6   Marketing        600.0    100.0
7       Sales        500.0    300.0
8     Support        400.0    120.0
9       Sales        500.0    500.0
10        NaN          NaN      NaN
11        NaN          NaN      NaN
12        NaN          NaN      NaN
13        NaN          NaN      NaN
14        NaN          NaN      NaN

In [ ]:
selection_2 = data[['Customer','Quantity','UnitPrice']]
print(selection_2)

   Customer  Quantity  UnitPrice
0      C001       2.0      250.0
1      C002       3.0       50.0
2      C003       1.0      300.0
3      C004      10.0       20.0
4      C005       2.0       80.0
5      C006       5.0      220.0
6      C007       1.0      100.0
7      C008      20.0       15.0
8      C009       2.0       60.0
9      C010       1.0      500.0
10      NaN       NaN        NaN
11      NaN       NaN        NaN
12      NaN       NaN        NaN
13      NaN       NaN        NaN
14      NaN       NaN        NaN

In [ ]:
# FIltering
filter = selection_2[selection_2['Quantity']>5]
filter

  Customer  Quantity  UnitPrice
3     C004      10.0       20.0
7     C008      20.0       15.0

In [ ]:
filter_1 = selection_2[selection_2['Quantity']>=5]
filter_1

  Customer  Quantity  UnitPrice
3     C004      10.0       20.0
5     C006       5.0      220.0
7     C008      20.0       15.0

In [ ]:
#Printing variable that matches my exact command. In this case, i just want value 5
filter_2 = selection_2[selection_2['Quantity']==5]
print(filter_2)

  Customer  Quantity  UnitPrice
5     C006       5.0      220.0

In [ ]:
filter_3 = selection_2[selection_2['Quantity']<=5]
filter_3

  Customer  Quantity  UnitPrice
0     C001       2.0      250.0
1     C002       3.0       50.0
2     C003       1.0      300.0
4     C005       2.0       80.0
5     C006       5.0      220.0
6     C007       1.0      100.0
8     C009       2.0       60.0
9     C010       1.0      500.0

In [ ]:
#not equals to 5. Remove anything that is equal to 5
filter_4 = selection_2[selection_2['Quantity']!=5]
print(filter_4)

   Customer  Quantity  UnitPrice
0      C001       2.0      250.0
1      C002       3.0       50.0
2      C003       1.0      300.0
3      C004      10.0       20.0
4      C005       2.0       80.0
6      C007       1.0      100.0
7      C008      20.0       15.0
8      C009       2.0       60.0
9      C010       1.0      500.0
10      NaN       NaN        NaN
11      NaN       NaN        NaN
12      NaN       NaN        NaN
13      NaN       NaN        NaN
14      NaN       NaN        NaN

In [ ]:
# Sorting data
sorting = selection_2.sort_values(by='Customer')
sorting

   Customer  Quantity  UnitPrice
0      C001       2.0      250.0
1      C002       3.0       50.0
2      C003       1.0      300.0
3      C004      10.0       20.0
4      C005       2.0       80.0
5      C006       5.0      220.0
6      C007       1.0      100.0
7      C008      20.0       15.0
8      C009       2.0       60.0
9      C010       1.0      500.0
10      NaN       NaN        NaN
11      NaN       NaN        NaN
12      NaN       NaN        NaN
13      NaN       NaN        NaN
14      NaN       NaN        NaN

In [ ]:
sorting_1 = selection_2['Customer']
sorting_1

0     C001
1     C002
2     C003
3     C004
4     C005
5     C006
6     C007
7     C008
8     C009
9     C010
10     NaN
11     NaN
12     NaN
13     NaN
14     NaN
Name: Customer, dtype: object

In [ ]:
selection_3 = data[['ProductCategory','Quantity']]
print(selection_3)

   ProductCategory  Quantity
0      Electronics       2.0
1          Fashion       3.0
2      Electronics       1.0
3        Groceries      10.0
4          Fashion       2.0
5      Electronics       5.0
6          Fashion       1.0
7        Groceries      20.0
8          Fashion       2.0
9      Electronics       1.0
10             NaN       NaN
11             NaN       NaN
12             NaN       NaN
13             NaN       NaN
14             NaN       NaN

In [ ]:
df_sorted_2 = selection_3.sort_values(by="ProductCategory", ascending=False)
df_sorted_2

   ProductCategory  Quantity
3        Groceries      10.0
7        Groceries      20.0
1          Fashion       3.0
4          Fashion       2.0
6          Fashion       1.0
8          Fashion       2.0
0      Electronics       2.0
2      Electronics       1.0
5      Electronics       5.0
9      Electronics       1.0
10             NaN       NaN
11             NaN       NaN
12             NaN       NaN
13             NaN       NaN
14             NaN       NaN

In [ ]:
selection_4 = data[['ProductCategory','Gender','Quantity']]
print(selection_4)

   ProductCategory  Gender  Quantity
0      Electronics  Female       2.0
1          Fashion    Male       3.0
2      Electronics  Female       1.0
3        Groceries    Male      10.0
4          Fashion  Female       2.0
5      Electronics    Male       5.0
6          Fashion  Female       1.0
7        Groceries    Male      20.0
8          Fashion  Female       2.0
9      Electronics    Male       1.0
10             NaN     NaN       NaN
11             NaN     NaN       NaN
12             NaN     NaN       NaN
13             NaN     NaN       NaN
14             NaN     NaN       NaN

In [ ]:
df_sorted_4 = selection_4.sort_values(by=["Gender","ProductCategory"])
df_sorted_4

   ProductCategory  Gender  Quantity
0      Electronics  Female       2.0
2      Electronics  Female       1.0
4          Fashion  Female       2.0
6          Fashion  Female       1.0
8          Fashion  Female       2.0
5      Electronics    Male       5.0
9      Electronics    Male       1.0
1          Fashion    Male       3.0
3        Groceries    Male      10.0
7        Groceries    Male      20.0
10             NaN     NaN       NaN
11             NaN     NaN       NaN
12             NaN     NaN       NaN
13             NaN     NaN       NaN
14             NaN     NaN       NaN

In [ ]:
#Adding a column to a selection

In [79]:
selection_5 = data[['OrderDate','ProductCategory','Revenue']]
selection_5

     OrderDate ProductCategory  Revenue
0   05/01/2025     Electronics    500.0
1   07/01/2025         Fashion    150.0
2   10/01/2025     Electronics    300.0
3   12/01/2025       Groceries    200.0
4   15/01/2025         Fashion    160.0
5   20/01/2025     Electronics   1100.0
6   22/01/2025         Fashion    100.0
7   25/01/2025       Groceries    300.0
8   28/01/2025         Fashion    120.0
9   01/02/2025     Electronics    500.0
10         NaN             NaN      NaN
11         NaN             NaN      NaN
12         NaN             NaN      NaN
13         NaN             NaN      NaN
14         NaN             NaN      NaN

In [90]:
selection_5['Tax'] = selection_5['Revenue']*0.10
selection_5

C:\Users\abass\AppData\Local\Temp\ipykernel_14740\1865409212.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selection_5['Tax'] = selection_5['Revenue']*0.10

     OrderDate ProductCategory  Revenue    Tax
0   05/01/2025     Electronics    500.0   50.0
1   07/01/2025         Fashion    150.0   15.0
2   10/01/2025     Electronics    300.0   30.0
3   12/01/2025       Groceries    200.0   20.0
4   15/01/2025         Fashion    160.0   16.0
5   20/01/2025     Electronics   1100.0  110.0
6   22/01/2025         Fashion    100.0   10.0
7   25/01/2025       Groceries    300.0   30.0
8   28/01/2025         Fashion    120.0   12.0
9   01/02/2025     Electronics    500.0   50.0
10         NaN             NaN      NaN    NaN
11         NaN             NaN      NaN    NaN
12         NaN             NaN      NaN    NaN
13         NaN             NaN      NaN    NaN
14         NaN             NaN      NaN    NaN

In [91]:
del selection_5['OrderDate']
print(selection_5)

   ProductCategory  Revenue    Tax
0      Electronics    500.0   50.0
1          Fashion    150.0   15.0
2      Electronics    300.0   30.0
3        Groceries    200.0   20.0
4          Fashion    160.0   16.0
5      Electronics   1100.0  110.0
6          Fashion    100.0   10.0
7        Groceries    300.0   30.0
8          Fashion    120.0   12.0
9      Electronics    500.0   50.0
10             NaN      NaN    NaN
11             NaN      NaN    NaN
12             NaN      NaN    NaN
13             NaN      NaN    NaN
14             NaN      NaN    NaN