R Data Frame
- An R data frame is a table-like structure used to store data in a row and columns similar to Excel spreadsheets and SQL table. In a simple term, it is a collection of columns, where each column can have a different data type.
- Data frames are displayed ina format as a table
- Data frames can have different types of data inside it. While the first column can be a character, the second and third can be numeric or logical.
- Each column must be uniform in their data type

Key features of Data Frame
- 2 dimensional (rows x columns)
- columns can have different data types (numeric, character, logical etc).
- Each column is a vector
- Most commonly used structure in Data Analysis.

In [ ]:
# Creating a data frame
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)
# Print the data frame
Data_Frame

  Training Pulse Duration
1 Strength 100   60
2 Stamina  150   30
3 Other    120   45

In [ ]:
# Summarizing our data: Use the summarize() function to summarize the data in a data frame.
# It gives a quick statistical overview of each column
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)
Data_Frame
# Summarize the data frame
summary(Data_Frame)

  Training Pulse Duration
1 Strength 100   60
2 Stamina  150   30
3 Other    120   45

   Training             Pulse          Duration
 Length:3           Min.   :100.0   Min.   :30.0
 Class :character   1st Qu.:110.0   1st Qu.:37.5
 Mode  :character   Median :120.0   Median :45.0
                    Mean   :123.3   Mean   :45.0
                    3rd Qu.:135.0   3rd Qu.:52.5
                    Max.   :150.0   Max.   :60.0

In [ ]:
# Access items: we can use single brackets[], double brackets[[]] or $ to access columns from a data frame:
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame[1] # This returns the first column but as a data frame and not a vector
Data_Frame[["Training"]] # This extracts the column as a vector
Data_Frame$Training
Data_Frame[["Pulse"]]
Data_Frame[["Duration"]]
Data_Frame["Pulse"]

  Training
1 Strength
2 Stamina
3 Other

[1] "Strength" "Stamina"  "Other"

[1] "Strength" "Stamina"  "Other"

[1] 100 150 120

[1] 60 30 45

  Pulse
1 100
2 150
3 120

Note:

[] means give me a table.
[[]] means give me the actual column values.
$ means shortcut to get the column

In [ ]:
# Add rows: You use the rbind() to add new rows in a data frame.
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)
# Add a new row
New_row_DF <- rbind(Data_Frame, c("Energy", 110, 110))
# Print the new row
New_row_DF

# Note: rbind() stacks data frames like placing one table on top of another.

  Training Pulse Duration
1 Strength 100   60
2 Stamina  150   30
3 Other    120   45
4 Energy   110   110

In [ ]:
# Add rows: You use the cbind() to add new colums in a data frame.
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)
# Add a new column
New_column_DF <- cbind(Data_Frame, steps = c(1000, 6000, 2000))
# Print the new column
New_column_DF

# Note: rbind() stacks data frames like placing one table on top of another.

  Training Pulse Duration steps
1 Strength 100   60       1000
2 Stamina  150   30       6000
3 Other    120   45       2000

In [ ]:
# Removing rows and columns: Use the c() to remove rows and columns in a data
# Example
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)
# Remove the first row and first column.
Data_Frame_New <- Data_Frame[-c(1), -c(1)]
# Print the new data frame
Data_Frame_New

# Finding the amount of rows and columns, you use the dim().
dim(Data_Frame_New)
dim(Data_Frame)

# Finding the length of data frame, use the length(): It is finding the number of columns in a Data Frame (similar to ncol() in python).
length(Data_Frame)
length(Data_Frame_New)

  Pulse Duration
2 150   30
3 120   45

[1] 2 2

[1] 3 3

[1] 3

[1] 2

## Combining Data Frames

Use the rbind() function to combine two or more data frames in R vertically:

In [ ]:
# Example
Data_Frame1 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame2 <- data.frame (
  Training = c("Stamina", "Stamina", "Strength"),
  Pulse = c(140, 150, 160),
  Duration = c(30, 30, 20)
)

New_Data_Frame <- rbind(Data_Frame1, Data_Frame2)
New_Data_Frame

  Training Pulse Duration
1 Strength 100   60
2 Stamina  150   30
3 Other    120   45
4 Stamina  140   30
5 Stamina  150   30
6 Strength 160   20

In [ ]:
### And use the cbind() function to combine two or more data frames in R horizontally:
# Example
Data_Frame3 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame4 <- data.frame (
  Steps = c(3000, 6000, 2000),
  Calories = c(300, 400, 300)
)

New_Data_Frame1 <- cbind(Data_Frame3, Data_Frame4)
New_Data_Frame1

  Training Pulse Duration Steps Calories
1 Strength 100   60       3000  300
2 Stamina  150   30       6000  400
3 Other    120   45       2000  300