R Matrices: A matrix is a two dimensional data set with rows and columns. A column is a vertical representation of data, while a row is a horizontal representation of data. A matrix can be created with the matrix() function. Specify the nrow and ncol parameters to get the amount of rows and columns. A matrix in R is a collection of nelements (usually numbers) arranged in a tabular format with rows (horizontal) and columns (vertical).

In [11]:
# Example
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2) # Note: Remember the c() function is used to concatenate items together.
thismatrix

     [,1] [,2]
[1,] 1    4
[2,] 2    5
[3,] 3    6

In [12]:
# I am telling R to fill row-wise. The default (as seen above) is column-wise.
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2, byrow = TRUE) # Note: Remember the c() function is used to concatenate items together.
thismatrix

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

Key Features of R Matrices.
- All elements in a matrix must be of the same type (vector-type features).

- You can access elements using [row, column]

In [13]:
# You can also create a mtrix with strings:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
thismatrix

     [,1]   [,2]
[1,] apple  cherry
[2,] banana orange

In [14]:
# Access Matrix items: You can access the items by using [] brackets. The first number "1" in the bracket specifies the row position, while the second number "2" specifies the column position.
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
thismatrix[1, 2]

[1] "cherry"

In [15]:
# The whole row can be accessed if you specify a comma after the number in the bracket.
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
thismatrix[2,]

# Similarly, the whole column can be accessed if you specify a comma before the number in the bracket:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
thismatrix[,2]

# Note: R returns the result as a vector, not as a matrix.
# Note: and a vector in R is always displayed in a straight line.

[1] "banana" "orange"

[1] "cherry" "orange"

In [19]:
# Access More Than One Row: More than one row can be accessed if you have the c() function:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)
thismatrix[c(1,2),] # c(1,2) is combining the 1st row and 2nd column. However, including the "," then means that it will pick everything on the line of apple and banana

     [,1]   [,2]   [,3]
[1,] apple  orange pear
[2,] banana grape  melon

In [20]:
# Access More Than One Column: More than one column can be accessed if you use the c() function.
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)
thismatrix[, c(1,2)]

     [,1]   [,2]
[1,] apple  orange
[2,] banana grape
[3,] cherry pineapple

In [22]:
# Add rows and columns
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)
newmatrix <- cbind(thismatrix, c("strawberry", "blueberry", "raspberry"))
newmatrix
# The cells in the new column must be of the same length as the existing matrix.

     [,1]   [,2]      [,3]  [,4]
[1,] apple  orange    pear  strawberry
[2,] banana grape     melon blueberry
[3,] cherry pineapple fig   raspberry

In [25]:
# Use the rbind() function to add additional rows in matrix
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)
newmatrix <- rbind(thismatrix, c("strawberry", "blueberry", "raspberry"))
newmatrix

     [,1]       [,2]      [,3]
[1,] apple      orange    pear
[2,] banana     grape     melon
[3,] cherry     pineapple fig
[4,] strawberry blueberry raspberry

In [32]:
# Remove Rows and Columns: Use the c() function to remove rows and columns in a Matrix:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol = 2)
thismatrix <- thismatrix[-c(1), -c(1)]
thismatrix

#| syntax    | Meaning      |
#| --------- | ------------ |
#| "c(1,2)"  | Select items |
#| "-c(1,2)" | Remove items |

[1] "mango"     "pineapple"

In [33]:
# Check if an item Exists:
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
"apple" %in% thismatrix

[1] TRUE

In [34]:
# Numbers of Rows and Columns: Use the dim() function to find the number of rows and columns in a Matrix.
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
dim(thismatrix)

[1] 2 2

In [35]:
# Matrix Length
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
length(thismatrix)
# Total cells in the matrix is the number of rows multiplied by the number of columns.
In the example above: Dimension = 2*2 = 4

[1] 4

In [38]:
# Loop Through a Matrix
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
for (rows in 1:nrow(thismatrix)) {
  for (columns in 1:ncol(thismatrix)) {
    print(thismatrix[rows, columns])
  }
}

[1] "apple"
[1] "cherry"
[1] "banana"
[1] "orange"