Arrays: In R programming, an array is a data structure used to store elements of the same data type in multiple dimension (more than just rows and columns).

Compared to matrices, arrays can have more than 2 dimensions...An R array is like an extension of a matrix that can have 2, 3, or more dimensions.

We can use the array() to create an array, and the dim parameter to specify the dimensions.

In [5]:
# Create a 3D array

arr <- array(1:12, dim = c(2,3,2)) # 2 rows, 3 columns, 2 layers
arr

# The two (2) layers are;
# 1 3 5         # 7 9 11
# 2 4 6         # 8 10 12

# To get the first layer
layer1 <- arr[ , , 1]
layer1

# To get the second layer
layer2 <- arr[ , , 2]
layer2

layer3 <- arr[2,3,2]
layer3

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

     [,1] [,2] [,3]
[1,] 7     9   11
[2,] 8    10   12

[1] 12

In [6]:
# Access Array Items: You can access the arrfay elements by referring to the index positions. You can use the [] brackets to access the desired elements from an array.
# Example
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[2,3,2]

# As an assignment, bring out the layers

[1] 22

In [7]:
# The syntax is as follow: array[row position, column position, matrix level]

# You can also access the whole row and column from a matrix in an array, by using the c() function.

# Example
thisarray <- c(1:24)

# Access all the items from the first row from matrix one.
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[c(1),,1] # c(1)    => Row 1
                    # (blank) => All columns
                    # 1       => First Layer
                    # Summary => Returns Row 1 across all columns in layer 1

# Access all the items from the first column from matrix one.
multiarray <- array(thisarray, dim = c(4, 3, 2))
multiarray[,c(1),1] # (blank)    => All rows
                    # c(1)       => Column 1
                    # 1          => First Layer
                    # Summary => Returns column 1 across all rows in layer 1

[1] 1 5 9

[1] 1 2 3 4

In [18]:
# Check is an element exists: To find out if a specified item is present in an array, use the %in% operator.
# Check if the value "2" is present in the array
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4,3,2))

2 %in% multiarray # %in% checks? # Is this value inside this objects?
                               # R searches through all elements in the array, and if it finds 2 in the array, it results TRUE.

layer1 <- arr[ , , 1]
layer1

# check multiple values
c(2, 50) %in% multiarray

# check if any value exists
any(c(50, 2) %in% multiarray)

# check if all values exists
all(c(1, 2, 3, 4) %in% multiarray)

[1] TRUE

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

[1]  TRUE FALSE

[1] TRUE

[1] TRUE

In [19]:
# Amount of Rows and Columns: Use the dim() function to find the amount of rows and columns in an array:
# Example
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))
dim(multiarray)

[1] 4 3 2

In [20]:
# Array Length: Use the length() function to find the dimension of an array.
# Example:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))
length(multiarray)

[1] 24

In [21]:
# Loop through an Array: You can loop through the array items using a for loop:
# Example
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))
for(x in multiarray) {
  print(x)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24